// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "wb-project/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// OrderCache is an autogenerated mock type for the OrderCache type
type OrderCache struct {
	mock.Mock
}

// Get provides a mock function with given fields: uid
func (_m *OrderCache) Get(uid string) (*models.Order, bool) {
	ret := _m.Called(uid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *models.Order
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (*models.Order, bool)); ok {
		return rf(uid)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Order); ok {
		r0 = rf(uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(uid)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Set provides a mock function with given fields: uid, order
func (_m *OrderCache) Set(uid string, order *models.Order) {
	_m.Called(uid, order)
}

// NewOrderCache creates a new instance of OrderCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderCache {
	mock := &OrderCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
